name: C/C++ CI

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Install eigen3
          run: sudo apt install libeigen3-dev
        - name: Run tests
          run: ./build.sh
